project_id = "zympnpibhohnxsnbxtaf"

[functions.create-subscription]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true

[functions.stripe-connect]
verify_jwt = true

[functions.tradingview-health-check]
verify_jwt = false

[functions.tradingview-service]
verify_jwt = true

[functions.trial-cleanup]
verify_jwt = false

[functions.subscription-webhook]
verify_jwt = false

[functions.create-program-prices]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
